org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=C:/Program Files/Zulu/zulu-25

loader_version=0.19.5

mod_id=pauth
mod_name=PAuth
mod_version=1.0.0
mod_group_id=ru.zaralx.pauth
mod_authors=zaralX
mod_description=Server-side mod for offline and online auth with automatic premium detection
